trigger:
  branches:
    include:
      - main  # Runs on main branch push 

pool:
  name: Default  

stages:
- stage: Build
  displayName: 'Build .NET API'
  jobs:
  - job: Build
    steps:
    - checkout: self  

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
        includePreviewVersions: true  

    - script: |
        dotnet build --configuration Release
      displayName: 'Build with .NET'

    - script: |
        dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/myapp
      displayName: 'dotnet publish'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/myapp'
        artifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureWebApp@1
      inputs:
        appType: webApp      
        azureSubscription: '$(azSub)'
        appName: 'FoodDiary'
        package: '$(System.ArtifactsDirectory)/drop'
